---
language: go
go:
    - 1.4.2
    - 1.5.1
    - release
install:
    - go get github.com/op/go-logging
    - go get github.com/fsouza/go-dockerclient
    - go get github.com/golang/lint/golint
    - go get github.com/fzipp/gocyclo
script:
    - make lint
    - make test
after_success:
    - bash <(curl -s https://codecov.io/bash)
