---
language: go
go:
    - 1.5.1
install:
    - go get github.com/op/go-logging
    - go get github.com/fsouza/go-dockerclient
    - go get golang.org/x/lint/golint
    - go get github.com/fzipp/gocyclo
script:
    - make lint
    - make test
after_success:
    - go get github.com/axw/gocov/gocov
    - go get github.com/mattn/goveralls
    - goveralls -repotoken $COVERALLS_TOKEN
